import type { Creature, Artifact, Gadget, ArtifactId } from "@shared/schema";

export const CREATURES: Creature[] = [
  {
    id: "glitch_fox",
    name: "Glitch Fox",
    type: "Tech",
    rarity: "uncommon",
    description: "A fox-shaped entity made of flickering pixels. Its tail phases between dimensions.",
    lore: "Locals say it only appears when old electronics short-circuit, drawn to the sharp tang of burning ozone and sparking wires. It feeds on corrupted data, grazing on the fragmented memories stored in discarded hard drives. Some claim that if you follow its flickering, geometric path through the woods, it will lead you to places where the fabric of reality has unspooled.",
    cipherClue: "WYH OLEUDUB YSOGV D VHFUHW USSP EHYLQG VYHOI VHKHQ",
    decodedSecret: "THE LIBRARY HOLDS A SECRET ROOM BEHIND SHELF SEVEN",
    weakAgainst: "Nature",
    strongAgainst: "Weird",
    locations: ["library", "school"],
    battlePower: 6,
    friendliness: 5,
    artSymbol: ">>",
  },
  {
    id: "moss_golem",
    name: "Moss Golem",
    type: "Nature",
    rarity: "common",
    description: "A lumbering creature of tangled roots and ancient moss. Moves slowly but hits hard.",
    lore: "This golem predates the town by centuries, its massive form shaped by the slow accumulation of earth, tangled roots, and damp forest debris. It moves with a glacial, deliberate pace, ignoring travelers unless they stray too close to the ancient ruins it watches over. Legends say it guards something buried deep in the forest—a remnant of a time before human feet ever touched the soil.",
    cipherClue: "EHQHDWY WYH SOGHVW SDN OLHV ZYDW ZDV QHKHU ISXQG",
    decodedSecret: "BENEATH THE OLDEST OAK LIES WHAT WAS NEVER FOUND",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["forest"],
    battlePower: 7,
    friendliness: 6,
    artSymbol: "##",
  },
  {
    id: "mirror_shade",
    name: "Mirror Shade",
    type: "Weird",
    rarity: "rare",
    description: "It looks exactly like you, but wrong. Slightly too tall. Smile slightly too wide.",
    lore: "Nobody knows where it came from, as the school's old mirror was smashed years ago after a series of unsettling incidents. It mimics human movements perfectly but always with a slight delay, its smile stretched just a fraction too wide, its eyes a shade too dark. Catching its gaze for too long leaves a lingering sense of paranoia, as if your own reflection might suddenly decide to step out and take your place.",
    cipherClue: "BSXU UHIOHFWLSQ NQSZV PSUH WYDQ BSX GS DVN LW",
    decodedSecret: "YOUR REFLECTION KNOWS MORE THAN YOU DO ASK IT",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["school"],
    battlePower: 8,
    friendliness: 3,
    artSymbol: "||",
  },
  {
    id: "void_moth",
    name: "Void Moth",
    type: "Shadow",
    rarity: "rare",
    description: "Wings like torn night sky. It doesn't fly — it falls upward, slowly.",
    lore: "The cave whispers its name before it appears, a sound like dry leaves scraping across stone. Three whispers and it arrives, its massive, ragged wings absorbing the little light that exists in the deep caverns. It doesn't fly so much as it alters gravity around itself, falling upward in a slow, hypnotic spiral that disorients anyone unfortunate enough to track its movement.",
    cipherClue: "WYH WYLUG FDKH FYDPEHU LV D GSSU QSW D GHDG HQG",
    decodedSecret: "THE THIRD CAVE CHAMBER IS A DOOR NOT A DEAD END",
    weakAgainst: "Weird",
    strongAgainst: "Nature",
    locations: ["cave"],
    battlePower: 9,
    friendliness: 2,
    artSymbol: "~~",
  },
  {
    id: "circuit_sprite",
    name: "Circuit Sprite",
    type: "Tech",
    rarity: "common",
    description: "Tiny and buzzing. Leaves a faint smell of ozone wherever it goes.",
    lore: "Found wherever the old power lines cross, these tiny, buzzing entities dart through the air like erratic fireflies. They leave behind a faint localized smell of ozone and the subtle hum of a transformer working in overdrive. Observers who have tracked their frenetic, jagged flight paths believe they aren't just flitting about randomly—they seem to be mapping a vast, invisible grid laid over the town.",
    cipherClue: "WYH RSZHU OLQHV ISUP D VBPESO ZYHQ VHHQ IUSP DESKH",
    decodedSecret: "THE POWER LINES FORM A SYMBOL WHEN SEEN FROM ABOVE",
    weakAgainst: "Nature",
    strongAgainst: "Weird",
    locations: ["forest", "library"],
    battlePower: 4,
    friendliness: 7,
    artSymbol: "**",
  },
  {
    id: "rumble_root",
    name: "Rumble Root",
    type: "Nature",
    rarity: "common",
    description: "Looks like a tangled ball of roots with two glowing amber eyes.",
    lore: "It rolls around making a low, continuous rumbling noise, resembling a tumbleweed constructed entirely of thick, knotted roots. Its two glowing amber eyes peer out from the center of the tangle, scanning for unknown threats. It becomes highly agitated near the cave entrance, vibrating aggressively and kicking up dirt, as if trying to warn travelers away from whatever slumbers below.",
    cipherClue: "VSPHWYLQJ EHOSZ WYH FDKH NHHRV JUSZLQJ XRZDUG",
    decodedSecret: "SOMETHING BELOW THE CAVE KEEPS GROWING UPWARD",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["forest", "cave"],
    battlePower: 3,
    friendliness: 8,
    artSymbol: "oo",
  },
  {
    id: "giggle_wisp",
    name: "Giggle Wisp",
    type: "Weird",
    rarity: "uncommon",
    description: "A floating blob of light that lets out unnerving laughter at random intervals.",
    lore: "It appears primarily between the dusty bookshelves on Tuesday evenings, manifesting as a floating, amorphous blob of pale pink light. It floats aimlessly, letting out unnerving, childlike laughter at completely random intervals that echoes through the quiet library. The local librarians have long given up trying to banish it, instead choosing to simply turn up the radio to drown out its periodic giggling.",
    cipherClue: "WYH ESSN WYDW ODXJYV LV QSW D ESSN DW DOO",
    decodedSecret: "THE BOOK THAT LAUGHS IS NOT A BOOK AT ALL",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["library"],
    battlePower: 5,
    friendliness: 6,
    artSymbol: "??",
  },
  {
    id: "phase_hound",
    name: "Phase Hound",
    type: "Shadow",
    rarity: "uncommon",
    description: "It walks through walls. Its footsteps make no sound but can be felt in your chest.",
    lore: "Only appearing in the abandoned east wing of the building, this ghostly canine walks effortlessly through solid matter. Its heavy footsteps make no audible sound in the air, but the rhythmic thud can be felt vibrating deep within your chest. The janitor strictly locks that hall every single night, not to keep trespassers out, but in a futile attempt to keep the hound's chilling presence contained.",
    cipherClue: "USSP WYLUWHHQ ZDV VHDOHG ISU D UHDVSQ QHKHU SRHQ LW",
    decodedSecret: "ROOM THIRTEEN WAS SEALED FOR A REASON NEVER OPEN IT",
    weakAgainst: "Weird",
    strongAgainst: "Nature",
    locations: ["school", "cave"],
    battlePower: 7,
    friendliness: 4,
    artSymbol: "//",
  },
  {
    id: "ember_newt",
    name: "Ember Newt",
    type: "Nature",
    rarity: "common",
    description: "A salamander with tiny flames where its spots should be. Warm to the touch.",
    lore: "Thrives near the secluded sections of the forest stream, precisely where a mysterious hidden hot spring bubbles to the surface. Small flames dance constantly along its slick back where typical amphibian spots should be, and its skin is surprisingly warm to the touch. They often gather in small clusters on damp rocks, heating the surrounding air and creating localized pockets of thick, ground-level fog.",
    cipherClue: "ISOOSZ WYH ZDUP ZDWHU XRVWUHDP WS ZYHUH LW EHJLQV",
    decodedSecret: "FOLLOW THE WARM WATER UPSTREAM TO WHERE IT BEGINS",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["forest"],
    battlePower: 3,
    friendliness: 9,
    artSymbol: "^~",
  },
  {
    id: "fog_wraith",
    name: "Fog Wraith",
    type: "Shadow",
    rarity: "common",
    description: "Indistinct and shifting, like fog given the vague shape of something ancient.",
    lore: "The town was tragically built on a geographic anomaly where a dense, clinging fog never fully dissipates. This creature is the reason why—an indistinct, shifting agglomeration of mist that occasionally takes on the terrifying, looming shape of something ancient and hungry. It drifts silently at the edges of the woods, waiting for wandering children or lost hikers to step into its chilling embrace.",
    cipherClue: "WYH WSZQ YDV D WZLQ DQG LW HALVWV LQ WYH ISJ",
    decodedSecret: "THE TOWN HAS A TWIN AND IT EXISTS IN THE FOG",
    weakAgainst: "Weird",
    strongAgainst: "Nature",
    locations: ["forest", "school"],
    battlePower: 4,
    friendliness: 5,
    artSymbol: "%%",
  },
  {
    id: "prism_beetle",
    name: "Prism Beetle",
    type: "Weird",
    rarity: "uncommon",
    description: "A beetle that refracts light in impossible directions. Standing near it makes you dizzy.",
    lore: "Operating on a biological wavelength beyond normal comprehension, it communicates purely in intense, strobing flashes of impossible colors. Standing too close to it as it refracts light in contradictory directions causes intense dizziness and mild hallucinations. Desperate researchers have filled entire shelves of notebooks trying to decode the syntax of its flashes, to no avail.",
    cipherClue: "UHG EOXH JUHHQ LQ WYDW SUGHU PHDQV GDQJHU LV QHDU",
    decodedSecret: "RED BLUE GREEN IN THAT ORDER MEANS DANGER IS NEAR",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["cave", "library"],
    battlePower: 5,
    friendliness: 7,
    artSymbol: "<>",
  },
  {
    id: "toxic_slime",
    name: "Toxic Slime",
    type: "Nature",
    rarity: "common",
    description: "A bubbling, sentient blob of luminous green chemicals. It absorbs anything that touches it.",
    lore: "According to recovered, half-melted lab notes, this biohazard started as an industrial-grade cleaning solution that inexplicably gained sentience on a quiet Tuesday afternoon. It now roams the tiled floors as a bubbling, luminous green blob, mindlessly absorbing and dissolving any organic matter it comes into contact with. It leaves a trail of smoking, pitted linoleum in its wake, smelling strongly of ammonia and burnt sugar.",
    cipherClue: "HARHULPHQW ISUWB VHKHQ ZDV QHKHU DXWYSULCHG",
    decodedSecret: "EXPERIMENT FORTY SEVEN WAS NEVER AUTHORIZED",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["lab"],
    battlePower: 4,
    friendliness: 7,
    artSymbol: "@@",
  },
  {
    id: "spark_golem",
    name: "Spark Golem",
    type: "Tech",
    rarity: "uncommon",
    description: "A hulking figure assembled from microscopes, beakers, and copper wire. Sparks fly when it moves.",
    lore: "Someone clearly built it from scratch, piecing together its hulking frame from discarded microscopes, oversized beakers, and miles of braided copper wire. Every heavy step it takes sends showers of blue sparks cascading across the floor. The only clue to its origin is a burned instruction manual found nearby, completely filled with an incomprehensible symbol code that no cryptographer has managed to crack.",
    cipherClue: "WYH JSOHP ZDV EXLOW WS JXDUG VSPHWYLQJ LQ WYH EDVHPHQW",
    decodedSecret: "THE GOLEM WAS BUILT TO GUARD SOMETHING IN THE BASEMENT",
    weakAgainst: "Water",
    strongAgainst: "Nature",
    locations: ["lab", "tower"],
    battlePower: 7,
    friendliness: 4,
    artSymbol: "$$",
  },
  {
    id: "flask_phantom",
    name: "Flask Phantom",
    type: "Weird",
    rarity: "rare",
    description: "A translucent figure swirling inside a massive flask. Its face keeps changing.",
    lore: "Bound seemingly forever within a massive, reinforced glass container, this translucent entity is trapped in a constant state of agonizing flux. Its ethereal face continuously melts and shifts into the agonized expressions of people long forgotten. The official laboratory log contains only a single, chilling entry regarding its origin: 'Dr. Emerson entered the flask room at 3pm, but the flask room has no door.'",
    cipherClue: "WYH RYDQWSP ZDV SQFH WYH YHDG VFLHQWLVW ZYS QHKHU OHIW",
    decodedSecret: "THE PHANTOM WAS ONCE THE HEAD SCIENTIST WHO NEVER LEFT",
    weakAgainst: "Nature",
    strongAgainst: "Shadow",
    locations: ["lab"],
    battlePower: 8,
    friendliness: 3,
    artSymbol: "()",
  },
  {
    id: "pixel_knight",
    name: "Pixel Knight",
    type: "Pixel",
    rarity: "uncommon",
    description: "A blocky warrior rendered in chunky pixels. Its sword is surprisingly sharp for something that shouldn't be three-dimensional.",
    lore: "Cabinet #7 has been completely unplugged from the wall for over twenty years, its screen coated in a thick layer of dust. Despite this, the knight routinely steps directly out of the broken glass, rendering itself into the real world as a blocky, low-resolution warrior. Its pixelated sword moves in choppy, stilted frames, yet the edge is astoundingly sharp, capable of slicing through modern steel like paper.",
    cipherClue: "WYH YLJY VFSUH WDEOH FSQWDLQV D PDR LI UHDG EDFNZDUGV",
    decodedSecret: "THE HIGH SCORE TABLE CONTAINS A MAP IF READ BACKWARDS",
    weakAgainst: "Glitch",
    strongAgainst: "Nature",
    locations: ["arcade"],
    battlePower: 6,
    friendliness: 5,
    artSymbol: "[]",
  },
  {
    id: "neon_serpent",
    name: "Neon Serpent",
    type: "Glitch",
    rarity: "rare",
    description: "A serpentine creature made of flickering neon tubes. It phases through arcade cabinets leaving trails of color.",
    lore: "The old arcade owner once muttered on his deathbed: 'The snake was always living in the wiring. It just finally learned how to be seen.' Now, it slithers effortlessly through the darkened arcade, phasing through heavy wooden cabinets while leaving trails of searing, colorful afterimages in the air. Its body is composed entirely of humming, high-voltage neon tubes that cast harsh shadows on the dirty carpet.",
    cipherClue: "ISOOSZ WYH QHSQ WUDLO DQG LW OHDGV WS RODBHU WZS",
    decodedSecret: "FOLLOW THE NEON TRAIL AND IT LEADS TO PLAYER TWO",
    weakAgainst: "Deep",
    strongAgainst: "Tech",
    locations: ["arcade", "lab"],
    battlePower: 9,
    friendliness: 2,
    artSymbol: "~~",
  },
  {
    id: "cabinet_ghost",
    name: "Cabinet Ghost",
    type: "Shadow",
    rarity: "common",
    description: "A faint, flickering shape inside an unpowered arcade cabinet. It replays the same level forever.",
    lore: "The arcade game it haunts was reportedly 99% complete when its sole developer vanished without a trace overnight. Now, this faint, flickering digital apparition is permanently trapped inside the unpowered cabinet, endlessly replaying the corrupted final level over and over. It silently mimes pushing buttons and pulling joysticks, desperately trying to achieve a victory condition that was never actually programmed into the code.",
    cipherClue: "LQVHUW FSLQ WS WDON WS WYH GHDG GHKHOSRHU",
    decodedSecret: "INSERT COIN TO TALK TO THE DEAD DEVELOPER",
    weakAgainst: "Pixel",
    strongAgainst: "Nature",
    locations: ["arcade", "school"],
    battlePower: 3,
    friendliness: 8,
    artSymbol: "{}",
  },
  {
    id: "tide_lurker",
    name: "Tide Lurker",
    type: "Water",
    rarity: "uncommon",
    description: "You never see all of it. Tentacles surface briefly, then withdraw. It's patient.",
    lore: "Local fishermen have frantically reported seeing segments of this massive entity for decades, though the town council always pretended not to hear them. You never witness its entirety at once; only thick, barnacle-encrusted tentacles that briefly breach the violent surf before smoothly withdrawing into the abyss. It is incredibly patient, willing to wait beneath the dark waves for years until the perfect moment to pull something—or someone—under.",
    cipherClue: "WYH GSFN VLQNV WYUHH LQFYHV HKHUB BHDU EXW QHKHU GLVDRRHDUV",
    decodedSecret: "THE DOCK SINKS THREE INCHES EVERY YEAR BUT NEVER DISAPPEARS",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["dock"],
    battlePower: 7,
    friendliness: 4,
    artSymbol: ")(",
  },
  {
    id: "rust_crab",
    name: "Rust Crab",
    type: "Nature",
    rarity: "common",
    description: "A crab with a shell made of barnacle-covered scrap metal. It clicks and whirs instead of scuttling.",
    lore: "Superstitious dock workers routinely leave out handfuls of rusty bolts and bent nails at the end of their shifts as appeasement offerings. These bizarre crustaceans, with shells cobbled together from sharp, barnacle-covered scrap metal, always emerge from the water to claim the hardware by morning. As they scavenge along the shore, they don't scuttle quietly; instead, they produce loud, rhythmic clicks and mechanical whirs like malfunctioning clockwork.",
    cipherClue: "WYH FUDEV EXLOG WYHLU VYHOOV IUSP VXQNHQ VYLRV",
    decodedSecret: "THE CRABS BUILD THEIR SHELLS FROM SUNKEN SHIPS",
    weakAgainst: "Water",
    strongAgainst: "Tech",
    locations: ["dock", "cave"],
    battlePower: 4,
    friendliness: 7,
    artSymbol: "^^",
  },
  {
    id: "depth_angler",
    name: "Depth Angler",
    type: "Deep",
    rarity: "rare",
    description: "A deep-sea creature that shouldn't be this close to shore. Its lure glows with false promises.",
    lore: "A terrifying predator from the crushingly deep ocean trenches, it has inexplicably found its way to the shallow, murky waters near the shore. Its bioluminescent lure glows with a mesmerizing, seemingly benevolent light that promises safety and warmth to the lost. The old dock master's final, frantic log entry warned: 'Something breathtakingly beautiful rose from the dark water. God forgive me, I should not have reached for it.'",
    cipherClue: "WYH OLJYW LW VYSZV BSX LV QSW UHDOOB WYHUH",
    decodedSecret: "THE LIGHT IT SHOWS YOU IS NOT REALLY THERE",
    weakAgainst: "Nature",
    strongAgainst: "Weird",
    locations: ["dock"],
    battlePower: 9,
    friendliness: 1,
    artSymbol: "!!",
  },
  {
    id: "signal_wraith",
    name: "Signal Wraith",
    type: "Tech",
    rarity: "rare",
    description: "A wavering humanoid shape made of visible radio waves. You can hear it before you see it.",
    lore: "The massive broadcast tower was officially decommissioned and gutted of equipment in 1987. Yet, in late 2019, it began transmitting an overpowering, wordless broadcast, though no one had turned it on. This wraith is the physical manifestation of that rogue signal—a wavering, painfully bright humanoid shape constructed entirely of visible radio waves, emitting a piercing screech that shatters glass when it draws near.",
    cipherClue: "WXQH WS IUHTXHQFB CHUS DQG OLVWHQ WS ZYDW DQVZHUV",
    decodedSecret: "TUNE TO FREQUENCY ZERO AND LISTEN TO WHAT ANSWERS",
    weakAgainst: "Deep",
    strongAgainst: "Nature",
    locations: ["tower"],
    battlePower: 8,
    friendliness: 3,
    artSymbol: "}|",
  },
  {
    id: "frequency_bat",
    name: "Frequency Bat",
    type: "Shadow",
    rarity: "common",
    description: "Jet black with ears like satellite dishes. It echolocates using frequencies that shouldn't exist.",
    lore: "These jet-black, oversized creatures roost in huge numbers inside the rusted husk of the abandoned radio tower's main dish. They possess massive, dish-like ears and echolocate using impossible frequencies that vibrate on a dimensional level. When a swarm takes flight at twilight, their collective sonar completely disrupts cellular and radio signals, plunging the surrounding three blocks into total communicative darkness.",
    cipherClue: "WYH EDWV YHDU D IUHTXHQFB YXPDQV FDQQSW EXW VYSXOG",
    decodedSecret: "THE BATS HEAR A FREQUENCY HUMANS CANNOT BUT SHOULD",
    weakAgainst: "Pixel",
    strongAgainst: "Nature",
    locations: ["tower", "cave"],
    battlePower: 5,
    friendliness: 6,
    artSymbol: "}}",
  },
  {
    id: "static_owl",
    name: "Static Owl",
    type: "Weird",
    rarity: "uncommon",
    description: "An owl whose feathers are made of shifting static patterns. Its eyes display test patterns.",
    lore: "It perches motionlessly on the absolute highest antenna of the tower, its feathers a mesmerizing, shifting pattern of black and white television static. Instead of normal pupils, its large eyes endlessly display a rotating gallery of colorful, retro TV test patterns. Any security cameras aimed in its direction instantly glitch out, recording nothing but pure white snow and bursts of discordant audio feedback.",
    cipherClue: "WYH SZO VHHV LQ DOO VRHFWUXPV LQFOXGLQJ SQHV ZH ISUJSW",
    decodedSecret: "THE OWL SEES IN ALL SPECTRUMS INCLUDING ONES WE FORGOT",
    weakAgainst: "Tech",
    strongAgainst: "Shadow",
    locations: ["tower", "library"],
    battlePower: 6,
    friendliness: 5,
    artSymbol: "{{",
  },
  {
    id: "shelf_mimic",
    name: "Shelf Mimic",
    type: "Weird",
    rarity: "common",
    description: "It looks like an ordinary shelf until you notice it has too many surfaces and they're all watching you.",
    lore: "The late eccentric collector's meticulous inventory simply lists this impossible piece of furniture as 'acquired.' Yet, historical blueprints show that the shelf was firmly rooted in place long before the house itself was ever built around it. It appears to be an ordinary mahogany shelving unit until you walk past and realize its numerous reflective surfaces are subtly shifting, silently watching your every move.",
    cipherClue: "QSW HKHUBWYLQJ LQ WYH FSOOHFWLSQ ZDV FSOOHFWHG ZLOOLQJOB",
    decodedSecret: "NOT EVERYTHING IN THE COLLECTION WAS COLLECTED WILLINGLY",
    weakAgainst: "Deep",
    strongAgainst: "Nature",
    locations: ["house", "library"],
    battlePower: 5,
    friendliness: 6,
    artSymbol: "==",
  },
  {
    id: "dust_djinn",
    name: "Dust Djinn",
    type: "Shadow",
    rarity: "uncommon",
    description: "A swirling column of dust motes that takes vaguely human shapes. It smells like old libraries and regret.",
    lore: "Taking the vague, fleeting shape of a tall humanoid, this swirling column of illuminated dust motes smells overwhelmingly of ancient, decaying paper and profound regret. It never speaks above a ragged whisper as it drifts through the collection rooms. Each distinct whisper it utters is actually the stolen, deeply personal memory of someone who once held the strange, cursed objects stored within these walls.",
    cipherClue: "WYH GXVW UHPHPEHUV HKHUB YDQG WYDW WSXFYHG HKHUB SEMHFW",
    decodedSecret: "THE DUST REMEMBERS EVERY HAND THAT TOUCHED EVERY OBJECT",
    weakAgainst: "Water",
    strongAgainst: "Weird",
    locations: ["house"],
    battlePower: 7,
    friendliness: 4,
    artSymbol: "&&",
  },
  {
    id: "porcelain_watcher",
    name: "Porcelain Watcher",
    type: "Deep",
    rarity: "rare",
    description: "A pristine porcelain figure with eyes that follow you. It's warm to the touch despite being ceramic.",
    lore: "This pristine, delicately painted porcelain figure has cold, painted eyes that definitively track you as you move through the room. Unsettlingly, its smooth ceramic surface is always feverishly warm to the touch, like a living creature running a dangerous temperature. The collector's very first journal entry reads: 'Item #1. I did not find it in the ruins. It found me. I had to build the entire collection around it just to appease it.'",
    cipherClue: "WYH GSOO ZDV PDGH EHISUH GSOOV ZHUH LQKHQWHG",
    decodedSecret: "THE DOLL WAS MADE BEFORE DOLLS WERE INVENTED",
    weakAgainst: "Nature",
    strongAgainst: "Glitch",
    locations: ["house"],
    battlePower: 8,
    friendliness: 2,
    artSymbol: "::",
  },
];

export const ARTIFACTS: Record<string, Artifact> = {
  old_gear: {
    id: "old_gear",
    name: "Old Gear",
    description: "A brass gear from no known machine. Still ticking faintly.",
    icon: "settings",
  },
  glowing_mushroom: {
    id: "glowing_mushroom",
    name: "Glowing Mushroom",
    description: "A bioluminescent mushroom. Provides just enough light to read by.",
    icon: "zap",
  },
  shadow_dust: {
    id: "shadow_dust",
    name: "Shadow Dust",
    description: "Fine particles of pure darkness. Handle carefully.",
    icon: "moon",
  },
  circuit_board: {
    id: "circuit_board",
    name: "Circuit Board",
    description: "A chip from a device that shouldn't exist yet.",
    icon: "cpu",
  },
  strange_feather: {
    id: "strange_feather",
    name: "Strange Feather",
    description: "Iridescent and impossibly light. From no bird you've ever seen.",
    icon: "feather",
  },
  cave_crystal: {
    id: "cave_crystal",
    name: "Cave Crystal",
    description: "Pulses with a faint inner glow. Hums at a frequency you can almost hear.",
    icon: "gem",
  },
  ancient_book: {
    id: "ancient_book",
    name: "Torn Page",
    description: "A page from a book that predates the town. The text shifts when you look away.",
    icon: "book-open",
  },
  static_chip: {
    id: "static_chip",
    name: "Static Chip",
    description: "A microchip that plays white noise when held. Seems to suppress strange phenomena.",
    icon: "radio",
  },
  chemical_vial: {
    id: "chemical_vial",
    name: "Chemical Vial",
    description: "A vial of luminous, self-stirring liquid. The label is in a language that changes.",
    icon: "flask-conical",
  },
  pixel_shard: {
    id: "pixel_shard",
    name: "Pixel Shard",
    description: "A fragment of what looks like reality rendered at low resolution.",
    icon: "grid-2x2",
  },
  rusty_anchor: {
    id: "rusty_anchor",
    name: "Rusty Anchor",
    description: "A small anchor covered in barnacles that glow at night.",
    icon: "anchor",
  },
  signal_fragment: {
    id: "signal_fragment",
    name: "Signal Fragment",
    description: "A captured radio wave made solid. It vibrates in your pocket.",
    icon: "radio",
  },
  collector_key: {
    id: "collector_key",
    name: "Collector's Key",
    description: "An ornate key that fits no lock you've ever seen.",
    icon: "key",
  },
};

export const GADGETS: Gadget[] = [
  {
    id: "trap_camera",
    name: "Trap Camera",
    description: "One-time use when Studying a creature. Improves the quality of your observation.",
    effect: "study_bonus",
    recipe: [
      { artifactId: "circuit_board", quantity: 2 },
      { artifactId: "old_gear", quantity: 1 },
    ],
  },
  {
    id: "scanner",
    name: "Creature Scanner",
    description: "One use per encounter. Reveals a creature's type, power, and weakness before you engage.",
    effect: "reveal_type",
    recipe: [
      { artifactId: "circuit_board", quantity: 1 },
      { artifactId: "static_chip", quantity: 1 },
      { artifactId: "cave_crystal", quantity: 1 },
    ],
  },
  {
    id: "decoder_wheel",
    name: "Decoder Wheel",
    description: "One use per decode. Cracks a single cipher when you solve it in the Cipher Chamber.",
    effect: "unlock_cipher",
    recipe: [
      { artifactId: "ancient_book", quantity: 1 },
      { artifactId: "old_gear", quantity: 2 },
      { artifactId: "strange_feather", quantity: 1 },
    ],
  },
  {
    id: "map",
    name: "Location Map",
    description: "One use per exploration. Choose whether your first stop is a discovery, a puzzle, or a choice.",
    effect: "choose_first_scene",
    recipe: [
      { artifactId: "strange_feather", quantity: 1 },
      { artifactId: "cave_crystal", quantity: 1 },
      { artifactId: "ancient_book", quantity: 1 },
    ],
  },
];

export const LOCATIONS = [
  {
    id: "forest",
    name: "Whispering Forest",
    description: "Ancient trees that creak in no wind. Something watches from between them.",
    hint: "Nature and Shadow creatures lurk here.",
    color: "nature",
    icon: "trees",
    atmosphere: "Dense fog rolls between the roots. Branches claw at the pale sky.",
  },
  {
    id: "library",
    name: "Peculiar Library",
    description: "Books that rearrange themselves. A card catalog no one remembers making.",
    hint: "Tech and Weird creatures favor the stacks.",
    color: "tech",
    icon: "library",
    atmosphere: "The smell of old paper and ozone. Something rustles in the restricted section.",
  },
  {
    id: "school",
    name: "Abandoned School",
    description: "Closed for years. The chalkboards still have writing on them from unknown hands.",
    hint: "Weird and Shadow types haunt these halls.",
    color: "weird",
    icon: "school",
    atmosphere: "Lockers rattle with no one around. The bell rings on no schedule.",
  },
  {
    id: "cave",
    name: "Echo Cave",
    description: "Your voice comes back different. Sometimes it answers before you speak.",
    hint: "Shadow and Nature creatures dwell in the dark.",
    color: "shadow",
    icon: "mountain",
    atmosphere: "Darkness that seems to breathe. Crystals that shouldn't glow, do.",
  },
  {
    id: "lab",
    name: "The Glitched Laboratory",
    description: "Experiments ran without scientists. Equipment hums on its own.",
    hint: "Tech and Weird creatures lurk among the beakers.",
    color: "tech",
    icon: "flask-conical",
    atmosphere: "Flickering monitors cast green light. Something bubbles that shouldn't.",
  },
  {
    id: "arcade",
    name: "The Forgotten Arcade",
    description: "Machines run with no power. High scores from decades in the future.",
    hint: "Pixel and Shadow creatures haunt the cabinets.",
    color: "pixel",
    icon: "gamepad-2",
    atmosphere: "Neon flickers in the dark. A cabinet plays a game nobody programmed.",
  },
  {
    id: "dock",
    name: "The Drowned Dock",
    description: "A pier that sank but still appears at low tide. The water remembers.",
    hint: "Water and Deep creatures surface here.",
    color: "water",
    icon: "anchor",
    atmosphere: "Salt air and rotting wood. The water is too still.",
  },
  {
    id: "tower",
    name: "The Silent Radio Tower",
    description: "Broadcasts nobody hears. But something hears you.",
    hint: "Tech and Shadow creatures ride the signal.",
    color: "tech",
    icon: "radio",
    atmosphere: "Static crackles from nowhere. The antenna hums with purpose.",
  },
  {
    id: "house",
    name: "The Collector's House",
    description: "Someone collected strange things. Then disappeared.",
    hint: "Weird and Deep creatures guard the collection.",
    color: "weird",
    icon: "home",
    atmosphere: "Dust moves with intent. Every object has a story it wants to tell.",
  },
];

export const TYPE_COLORS: Record<string, string> = {
  Tech: "text-blue-400 dark:text-blue-300",
  Nature: "text-green-600 dark:text-green-400",
  Weird: "text-purple-500 dark:text-purple-400",
  Shadow: "text-slate-500 dark:text-slate-400",
  Pixel: "text-pink-500 dark:text-pink-400",
  Water: "text-sky-500 dark:text-sky-400",
  Glitch: "text-rose-500 dark:text-rose-400",
  Deep: "text-indigo-500 dark:text-indigo-400",
};

export const TYPE_BG: Record<string, string> = {
  Tech: "bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800",
  Nature: "bg-green-50 dark:bg-green-950 border-green-200 dark:border-green-800",
  Weird: "bg-purple-50 dark:bg-purple-950 border-purple-200 dark:border-purple-800",
  Shadow: "bg-slate-100 dark:bg-slate-900 border-slate-300 dark:border-slate-700",
  Pixel: "bg-pink-50 dark:bg-pink-950 border-pink-200 dark:border-pink-800",
  Water: "bg-sky-50 dark:bg-sky-950 border-sky-200 dark:border-sky-800",
  Glitch: "bg-rose-50 dark:bg-rose-950 border-rose-200 dark:border-rose-800",
  Deep: "bg-indigo-50 dark:bg-indigo-950 border-indigo-200 dark:border-indigo-800",
};

export const TYPE_BADGE: Record<string, string> = {
  Tech: "bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300",
  Nature: "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300",
  Weird: "bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300",
  Shadow: "bg-slate-200 text-slate-700 dark:bg-slate-800 dark:text-slate-300",
  Pixel: "bg-pink-100 text-pink-700 dark:bg-pink-900 dark:text-pink-300",
  Water: "bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-300",
  Glitch: "bg-rose-100 text-rose-700 dark:bg-rose-900 dark:text-rose-300",
  Deep: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900 dark:text-indigo-300",
};

export const RARITY_COLORS: Record<string, string> = {
  common: "text-muted-foreground",
  uncommon: "text-blue-500 dark:text-blue-400",
  rare: "text-yellow-600 dark:text-yellow-400",
};

export const CIPHER_REWARDS: Record<string, ArtifactId> = {
  Tech: "circuit_board",
  Nature: "glowing_mushroom",
  Weird: "ancient_book",
  Shadow: "shadow_dust",
  Pixel: "pixel_shard",
  Water: "rusty_anchor",
  Glitch: "signal_fragment",
  Deep: "collector_key",
};

export function getCipherReward(creatureId: string): ArtifactId | null {
  const creature = CREATURES.find((c) => c.id === creatureId);
  if (!creature) return null;
  return CIPHER_REWARDS[creature.type] || null;
}

export function getCreaturesForLocation(locationId: string): Creature[] {
  return CREATURES.filter((c) => c.locations.includes(locationId));
}

export function getRandomCreature(locationId: string): Creature {
  const pool = getCreaturesForLocation(locationId);
  const rarityWeights = { common: 5, uncommon: 3, rare: 1 };
  const weighted: Creature[] = [];
  pool.forEach((c) => {
    const w = rarityWeights[c.rarity];
    for (let i = 0; i < w; i++) weighted.push(c);
  });
  return weighted[Math.floor(Math.random() * weighted.length)];
}

const DROP_POOLS: Record<string, ArtifactId[]> = {
  Tech: ["circuit_board", "static_chip", "old_gear"],
  Nature: ["glowing_mushroom", "strange_feather", "cave_crystal"],
  Weird: ["strange_feather", "ancient_book", "cave_crystal"],
  Shadow: ["shadow_dust", "cave_crystal", "ancient_book"],
  Pixel: ["pixel_shard", "circuit_board", "old_gear"],
  Water: ["rusty_anchor", "cave_crystal", "glowing_mushroom"],
  Glitch: ["pixel_shard", "static_chip", "signal_fragment"],
  Deep: ["rusty_anchor", "shadow_dust", "collector_key"],
};

function pickFromPool(pool: ArtifactId[], count: number): ArtifactId[] {
  const result: ArtifactId[] = [];
  for (let i = 0; i < count; i++) {
    result.push(pool[Math.floor(Math.random() * pool.length)] as ArtifactId);
  }
  return result;
}

export function getArtifactsDropped(creature: Creature): ArtifactId[] {
  const pool = DROP_POOLS[creature.type];
  const count = creature.rarity === "rare" ? 2 : 1;
  return pickFromPool(pool, count);
}

/** Study always gives 1 artifact (2 if Trap Camera used). Safe option, no risk. */
export function getStudyDrops(creature: Creature, trapCameraUsed: boolean): ArtifactId[] {
  const pool = DROP_POOLS[creature.type];
  const count = trapCameraUsed ? 2 : 1;
  return pickFromPool(pool, count);
}
